CREATE TABLE USER (
  USER_ID int(10) NOT NULL AUTO_INCREMENT,
  LOGIN varchar(50) NOT NULL,
  PWD varchar(100) NOT NULL,
  ENABLED tinyint(1) DEFAULT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
 
CREATE TABLE ROLE (
  ROLE_ID int(10) NOT NULL AUTO_INCREMENT,
  USER_ID int(10) DEFAULT NULL,
  CODE varchar(60) NOT NULL,
  LABEL varchar(100) NOT NULL,
  PRIMARY KEY (ROLE_ID),
  CONSTRAINT FK_USROLE FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;